# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_accessrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='cateogry',
            new_name='category',
        ),
    ]
